#!/usr/bin/env bash
# Remove the files left behind by the restructuring. Both architectures are
# currently present side by side; this deletes the older one.
#
# Run from the project root, on a clean working tree:
#   git status            # nothing pending
#   bash cleanup.sh
#   git status            # review the deletions before committing

set -euo pipefail
cd "$(dirname "$0")"

echo "== superseded source modules =="
rm -fv src/absences.py src/cout.py src/donnees.py src/graines.py \
       src/modeles.py src/pertes.py src/preparation.py

echo "== ghost package directories, caches only, no source left =="
rm -rfv src/data src/features src/models src/evaluation
rm -rfv src/__pycache__ src/.ipynb_checkpoints

echo "== superseded scripts =="
rm -fv scripts/baseline_check.py scripts/inventaire.py \
       scripts/preparer.py scripts/verifier_cout.py

echo "== superseded notebooks =="
rm -fv notebooks/02_benchmark_ancien.ipynb notebooks/03_experiences.ipynb \
       notebooks/05_perte_cout.ipynb

echo "== superseded documents =="
rm -fv docs/CARTE.md docs/JOURNAL.md docs/JOURNAL_projet_2026-08-09.md \
       docs/traceabilite.md docs/protocole_biblio.md \
       docs/protocole_evaluation.md \
       docs/fiche_scania.md docs/fiche_metropt3.md docs/fiche_enginehealth.md

echo "== superseded result files =="
rm -fv reports/benchmark_log.txt reports/comparaisons_appariees.csv \
       reports/experiences.csv reports/fonctions_perte.csv \
       reports/variante_perceptron_retenue.json \
       reports/s1_sanity_check.txt reports/s2_dataset_report.txt
rm -rfv reports/metrics

echo "== superseded figures, f-prefix and the duplicated 0x- series =="
rm -fv reports/figures/f*.png
rm -fv reports/figures/01_missing_value_distribution.png \
       reports/figures/02_scatter_by_class.png \
       reports/figures/03_nesting.png \
       reports/figures/04_depth_vs_usage.png \
       reports/figures/05_imputation_effect.png \
       reports/figures/06_threshold_tuning.png \
       reports/figures/07_model_ranking.png \
       reports/figures/08_ablation.png \
       reports/figures/09_factorial_plan.png \
       reports/figures/10_loss_functions.png

echo "== superseded prepared data, regenerated by build_dataset.py =="
rm -fv data/processed/X_app_final.csv data/processed/X_val_final.csv \
       data/processed/y_app.csv \
       data/processed/extracteur_absences.joblib \
       data/processed/preparateur.joblib
rm -fv data/raw/aps_scania.zip

echo
echo "Done. Now:"
echo "  python scripts/build_dataset.py    # regenerate data/processed"
echo "  python -m pytest -q                # 5 modules, 40 tests"
echo "  python scripts/verify.py           # 23 checks"
